{{
    config(
        materialized='table'
    )
}}

WITH SNAPSHOT_TABLE AS (
SELECT  60000+row_number() OVER (ORDER BY PRODUCT_ID) AS PRODUCT_KEY ,* FROM {{ ref('STG_PRODUCT') }}
)
SELECT PRODUCT_KEY,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CLASS,DBT_VALID_FROM
         AS EFFECTIVE_FROM ,DBT_VALID_TO AS EFFECTIVE_TO,
         (CASE WHEN ST.DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS
          FROM SNAPSHOT_TABLE ST
