{{
    config(
        materialized='table'
    )
}}

WITH SNAPSHOT_TABLE AS (
SELECT  30000+row_number() OVER (ORDER BY ID) AS USER_KEY ,* FROM {{ ref('STG_USER') }}
)
SELECT USER_KEY,ID AS USER_ID,USERNAME AS USER_NAME,EMAIL,PHONE AS PHONE_NO,CITY,COMPANYNAME AS COMPANY_NAME,DBT_VALID_FROM
         AS EFFECTIVE_FROM ,DBT_VALID_TO AS EFFECTIVE_TO,
         (CASE WHEN ST.DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS
          FROM SNAPSHOT_TABLE ST

