{{
    config(
        materialized='table'
    )
}}

WITH DIM_ACCOUNT AS
(
    SELECT * FROM {{ ref('DIM_ACCOUNT') }}
),

DIM_USER AS 
(
    SELECT * FROM {{ ref('DIM_USER') }}
),

DIM_DATE AS 
(
    SELECT * FROM {{ source('FACT_DIM_DIM', 'DIM_DATE') }}
),

-- DIM_PAYMENT AS 
-- (
--     SELECT * FROM {{ ref('DIM_PAYMENT') }}
-- ),

-- DIM_PRODUCT AS
-- (
--     SELECT * FROM {{ ref('DIM_PRODUCT') }}
-- ),

STG_ORDER AS
(
SELECT ID ORDER_ID,OWNERID AS USER_ID,ACCOUNTID AS ACCOUNT_ID,CREATEDDATE AS CREATED_DATE,TOTALAMOUNT AS TOTAL_AMOUNT
        FROM {{ source('FACT_DIM_STG', 'STG_ORDER') }}
)

SELECT A.ACCOUNT_KEY,U.USER_KEY,D.DATE_KEY,O.TOTAL_AMOUNT
FROM DIM_ACCOUNT A,DIM_USER U,STG_ORDER O,DIM_DATE D
WHERE 
    A.ACCOUNT_ID=O.ACCOUNT_ID AND 
    U.USER_ID=O.USER_ID AND
    TO_TIMESTAMP_NTZ(O.CREATED_DATE) = TO_TIMESTAMP_NTZ(D.DATE_TIME)


-- SELECT * FROM {{ source('FACT_DIM_STG', 'STG_ORDER') }}