{{
    config(
        materialized='table'
    )
}}

WITH SNAPSHOT_TABLE AS (
SELECT  30000+row_number() OVER (ORDER BY USER_ID) AS USER_KEY ,* FROM {{ ref('USER') }}
)
SELECT USER_KEY,USER_ID,EMP_ID,USER_NAME,EMAIL,PHONE_NO,ADDRESS,COMPANY_NAME,DBT_VALID_FROM
         AS EFFECTIVE_FROM ,DBT_VALID_TO AS EFFECTIVE_TO,
         (CASE WHEN ST.DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS
          FROM SNAPSHOT_TABLE ST

