WITH FACT_ORDER AS
(
    SELECT * FROM {{ ref('FACT_ORDER') }}
),

ACCOUNT_ORDER AS
(
    SELECT F.USER_KEY,F.ACCOUNT_KEY,F.DATE_KEY,F.ORDER_ID,MAX(F.TOTAL_AMOUNT)
    FROM FACT_ORDER F
)

SELECT * FROM ACCOUNT_ORDER