{{
    config(
        materialized='table'
    )
}}

WITH SNAPSHOT_TABLE AS (

SELECT * FROM {{ ref('USER') }}
)

SELECT USER_ID,EMP_ID,USER_NAME,EMAIL,PHONE_NO,ADDRESS,COMPANY_NAME,DBT_VALID_FROM AS EFFECTIVE_FROM ,DBT_VALID_TO AS EFFECTIVE_TO,(CASE WHEN ST.DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS FROM SNAPSHOT_TABLE ST


-- EMP_ID
-- NAME
-- EMAIL
-- PHONE_NO
-- ADDRESS
-- COMPANY_NAME
-- DBT_SCD_ID
-- DBT_UPDATED_AT
-- DBT_VALID_FROM
-- DBT_VALID_TO