{{
    config(
        materialized='table'
    )
}}

WITH SNAPSHOT_TABLE AS (

SELECT * FROM {{ ref('mock_orders1') }}
)

SELECT ORDER_ID,STATUS AS ORDER_STATUS,CREATED_AT,UPDATED_AT,DBT_VALID_FROM,DBT_VALID_TO ,
(CASE WHEN ST.DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS FROM SNAPSHOT_TABLE ST